# Generated by Django 2.0.1 on 2018-01-22 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('isbn', models.IntegerField(unique=True)),
                ('author', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('reviewCount', models.IntegerField()),
                ('sellingPoint', models.IntegerField()),
                ('crawl_date', models.DateTimeField(default=datetime.datetime(2018, 1, 22, 13, 45, 0, 214740, tzinfo=utc))),
                ('pub_dateYear', models.IntegerField()),
                ('pub_dateMonth', models.IntegerField()),
                ('pub_dateDay', models.IntegerField()),
                ('cate_A', models.CharField(max_length=256)),
                ('cate_B', models.CharField(max_length=256)),
                ('cate_C', models.CharField(max_length=256)),
                ('cate_D', models.CharField(max_length=256)),
            ],
        ),
    ]
