# Generated by Django 2.0.1 on 2018-01-26 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_dateDay',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_dateMonth',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_dateYear',
        ),
        migrations.AddField(
            model_name='book',
            name='pubDate',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='book',
            name='translater',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='crawl_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 26, 13, 45, 50, 772073, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Publisher'),
        ),
    ]
