# Generated by Django 2.0.1 on 2018-01-26 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180126_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='crawl_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 26, 13, 47, 52, 710734, tzinfo=utc)),
        ),
    ]
