# Generated by Django 2.0.1 on 2018-02-04 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180204_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='crawl_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 4, 6, 28, 56, 145197, tzinfo=utc)),
        ),
    ]
