# Generated by Django 2.0.1 on 2018-02-04 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20180204_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cate_A',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cate_B',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cate_C',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cate_D',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='crawl_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 4, 8, 50, 30, 225223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviewCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='sellingPoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
