# Generated by Django 2.0.1 on 2018-02-04 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20180204_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='crawl_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 4, 8, 59, 29, 372534, tzinfo=utc)),
        ),
    ]
