# Generated by Django 2.0.1 on 2018-02-07 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20180207_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('reviewCount', models.IntegerField(blank=True, null=True)),
                ('sellingPoint', models.IntegerField(blank=True, null=True)),
                ('crawl_date', models.DateTimeField(default=datetime.datetime(2018, 2, 7, 10, 8, 11, 104553, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='crawl_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reviewCount',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sellingPoint',
        ),
        migrations.AddField(
            model_name='book',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='book.MetaData'),
        ),
    ]
