# Generated by Django 2.0.1 on 2018-02-07 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20180207_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='crawl_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 10, 38, 27, 226305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
