# Generated by Django 2.0.1 on 2018-02-07 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20180207_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='crawl_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 12, 39, 13, 449672, tzinfo=utc)),
        ),
    ]
