# Generated by Django 2.0.1 on 2018-02-07 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20180207_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='crawl_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 13, 5, 4, 295031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
