# Generated by Django 2.0.1 on 2018-02-08 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20180207_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Author_None', max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubDate',
            field=models.CharField(default='Pubdate_None', max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Publisher_None', max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Title_None', max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='translater',
            field=models.CharField(default='Translater_None', max_length=256),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='crawl_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 12, 28, 0, 440037, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='reviewCount',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='sellingPoint',
            field=models.IntegerField(default=-1),
        ),
    ]
