# Generated by Django 2.0.2 on 2018-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20180208_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='crawl_date',
            field=models.DateTimeField(),
        ),
    ]
