# Generated by Django 2.0.2 on 2018-02-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20180224_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cate_A',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cate_B',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cate_C',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cate_D',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
