# Generated by Django 2.0.2 on 2018-02-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20180228_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='None', max_length=1024),
        ),
    ]
