# Generated by Django 2.0.2 on 2018-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_metadata_rankriseandfall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='reviewCount',
            field=models.CharField(default='?', max_length=128),
        ),
    ]
