# Generated by Django 2.0.2 on 2018-03-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20180306_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
